# Configuration file for SLAM Toolbox
slam_toolbox:
  ros__parameters:
    # Robot frame settings
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping  # mapping or localization

    # SLAM Algorithm Parameters
    map_update_interval: 0.5  # 更频繁更新地图
    resolution: 0.05
    max_laser_range: 12.0  # 增大激光范围
    minimum_travel_distance: 0.02  # 减小移动阈值，更容易触发更新
    minimum_travel_heading: 0.05
    max_sequential_matching_failures: 10  # 增加容错

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_covariance: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Scan Matching Parameters
    scan_matcher_type: ceres_scan_matcher
    ceres_solver_options:
      use_nonmonotonic_steps: true
      max_num_iterations: 50
      num_threads: 2

    # Visualization and Debug
    debug_logging: true  # 启用调试日志
    publish_occupancy_map: true

    # Performance Settings
    threads: 2
    enable_interactive_mode: true
    
    # 启用Jazzy特定参数
    use_pose_extrapolator: true  # 解决TF相关错误
    map_start_pose: [0.0, 0.0, 0.0]  # 初始地图位置
    map_start_at_dock: true  # 从机器人当前位置开始建图
    
    # 额外参数
    transform_timeout: 0.5  # 增加TF超时
    pose_update_interval: 0.02  # 更频繁更新位姿
    use_scan_matching: true  # 确保使用扫描匹配
    
    # 新增参数
    use_map_saver: true  # 使用地图保存功能
    use_map_server: true  # 使用地图服务器（允许加载已有地图）
    serialize_map_to_file: true  # 定期将地图序列化到文件
    enable_interactive_mode: true  # 允许交互式地图编辑
    max_covariance_size: 100.0  # 增大协方差大小，提高鲁棒性
    save_map_period: 60.0  # 每分钟自动保存一次地图
    ceres_loss_function: HuberLoss  # 使用更鲁棒的损失函数 