slam_toolbox:
  ros__parameters:
    # Basic parameters
    use_sim_time: true
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    
    # Simple configuration
    mode: mapping
    debug_logging: true
    
    # Conservative update parameters
    transform_publish_period: 0.05
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 10.0